import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  wikiSidebar: [{ type: "autogenerated", dirName: "wiki" }],
  homelabSidebar: [{ type: "autogenerated", dirName: "homelab" }],
  minecraftSidebar: [{ type: "autogenerated", dirName: "minecraft-archives" }],
};

export default sidebars;
